#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running tcgpulls build process..."
cd tcgpulls && npx keystone prisma migrate dev && npm run build
echo "Build process for tcgpulls complete."
echo "Running tcgpulls-admin build process..."
cd ../tcgpulls-admin && npm run build
echo "Build process for tcgpulls-admin complete."
build_status=$?

if [ $build_status -ne 0 ]; then
  echo "Build(s) failed. Aborting commit."
  exit 1
fi

echo "Build(s) succeeded. Proceeding with commit."